### ISSUE TITLE
newrelic_infra_integration provider fails on Windows

### ISSUE THREAD

**Issue by haidangwa** [newrelic/infrastructure-agent-chef#62]
Using `newrelic_infra_agent` in a wrapper cookbook to configure nri-port-monitor on Windows, chef-client fails to converge. The error output is below.

```
       [2019-06-04T16:53:28-07:00] INFO: directory[/opt/newrelic-infra/nri-port-monitor/bin] created directory /opt/newrelic-infra/nri-port-monitor/bin
       
             - create new directory /opt/newrelic-infra/nri-port-monitor/bin
             ================================================================================
             Error executing action `create` on resource 'directory[/opt/newrelic-infra/nri-port-monitor/bin]'
             ================================================================================
       
             Chef::Exceptions::Win32APIError
             -------------------------------
             No mapping between account names and security IDs was done.
             ---- Begin Win32 API output ----
             System Error Code: 1332
             System Error Message: No mapping between account names and security IDs was done.
             ---- End Win32 API output ----
       
             Resource Declaration:
             ---------------------
             # In C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/newrelic-infra/libraries/integration.rb
       
       76:         directory dir do
       77:           owner new_resource.user
       78:           group new_resource.group
       79:           mode '0750'
       80:           recursive true
       81:         end
       82:       end
       
             Compiled Resource:
             ------------------
             # Declared in C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/newrelic-infra/libraries/integration.rb:76:in `block (2 levels) in <class:Integration>'
       
             directory("/opt/newrelic-infra/nri-port-monitor/bin") do
        action [:create]
        default_guard_interpreter :default
        declared_type :directory
        cookbook_name "twdc-newrelic-infra"
        path "/opt/newrelic-infra/nri-port-monitor/bin"
        recursive true
        mode "0750"
        owner "newrelic_infra"
        group "newrelic_infra"
             end
       
             System Info:
             ------------
             chef_version=13.12.14
             platform=windows
             platform_version=10.0.14393
             ruby=ruby 2.4.5p335 (2018-10-18 revision 65137) [x64-mingw32]
             program_name=C:/opscode/chef/bin/chef-client
             executable=C:/opscode/chef/bin/chef-client
       
       [2019-06-04T16:53:28-07:00] INFO: Running queued delayed notifications before re-raising exception
       
           ================================================================================
           Error executing action `create` on resource 'newrelic_infra_integration[nri-port-monitor]'
           ================================================================================
       
           Chef::Exceptions::Win32APIError
           -------------------------------
           directory[/opt/newrelic-infra/nri-port-monitor/bin] (C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/newrelic-infra/libraries/integration.rb line 76) had an error: Chef::Exceptions::Win32APIError: No mapping between account names and security IDs was done.
           ---- Begin Win32 API output ----
           System Error Code: 1332
           System Error Message: No mapping between account names and security IDs was done.
           ---- End Win32 API output ----
       
           Resource Declaration:
           ---------------------
           # In C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/twdc-newrelic-infra/recipes/host_integrations.rb
       
            43:   newrelic_infra_integration name do |infra_resource|
            44:     if properties['enabled'] == true && !properties['config']['instances'].empty?
            45:       action :create
            46:     else
            47:       action :remove
            48:     end
            49:     properties['config'].each do |property, value|
       
           Compiled Resource:
           ------------------
           # Declared in C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/twdc-newrelic-infra/recipes/host_integrations.rb:43:in `block in from_file'
       
           newrelic_infra_integration("nri-port-monitor") do
             action [:create]
             default_guard_interpreter :default
             declared_type :newrelic_infra_integration
             cookbook_name "twdc-newrelic-infra"
             recipe_name "host_integrations"
             bin "/opt/newrelic-infra/nri-port-monitor/bin/port-monitor"
             bin_dir "/opt/newrelic-infra/nri-port-monitor/bin"
             integration_name "com.newrelic.tcp-port-monitor"
             remote_url "https://nexus.somewhere.com/nexus/service/local/repositories/BLAH/content/newrelic/nri-port-monitor/1.2/nri-port-monitor-1.2.tar.gz"
             commands {"metrics"=>["--metrics"]}
             instances [{"name"=>"kitchen-nginx-80", "command"=>"metrics", "arguments"=>{"address"=>"127.0.0.1:80", "network"=>"tcp", "timeout"=>5}, "labels"=>{"environment"=>"test-kitchen"}}]
             definition_file "/var/db/newrelic-infra/custom-integrations/nri-port-monitor.yaml"
             config_file "/etc/newrelic-infra/integrations.d/nri-port-monitor.yaml"
           end
       
           System Info:
           ------------
           chef_version=13.12.14
           platform=windows
           platform_version=10.0.14393
           ruby=ruby 2.4.5p335 (2018-10-18 revision 65137) [x64-mingw32]
           program_name=C:/opscode/chef/bin/chef-client
           executable=C:/opscode/chef/bin/chef-client
              
```

From past experience, the provider for `newrelic_infra_integration` there are a few resources where `mode` is being given for directory and file resources. I believe these need to be converted to support Windows permissions.

These are the lines that I see using `mode`:
- https://github.com/newrelic/infrastructure-agent-chef/blob/master/libraries/integration.rb#L79
- https://github.com/newrelic/infrastructure-agent-chef/blob/master/libraries/integration.rb#L102
- https://github.com/newrelic/infrastructure-agent-chef/blob/master/libraries/integration.rb#L123

An example for Windows permissions that I have used in the past is given below:
```
    if platform_family?('windows')
      rights :read, 'Everyone', applies_to_children: true
      rights :full_control, 'Administrators', applies_to_children: true
      inherits true
    else
      mode '0755'
      owner 'root'
      group 'root'
    end
```

This error occurs on both Chef 13 and Chef 14. Test Platform was a Windows 2016 node in EC2 (running kitchen-ec2).

**Comment by haidangwa** [comment]
this might explain/help the `No mapping...` error: https://discourse.chef.io/t/windows-template-error/11181/2

**Comment by alejandrodnm** [comment]
Hi @haidangwa, I see that in your definition for `newrelic_infra_integration("nri-port-monitor")` you have this values which refer to linux paths 

```
             bin "/opt/newrelic-infra/nri-port-monitor/bin/port-monitor"
             bin_dir "/opt/newrelic-infra/nri-port-monitor/bin"
             definition_file "/var/db/newrelic-infra/custom-integrations/nri-port-monitor.yaml"
             config_file "/etc/newrelic-infra/integrations.d/nri-port-monitor.yaml"
``` 

The error you're getting is because chef is telling windows to create directories which are Linux paths 

```
Error executing action `create` on resource 'directory[/opt/newrelic-infra/nri-port-monitor/bin]'
```

**Comment by alejandrodnm** [comment]
Hi, @haidangwa I'm going to close the issue, but feel free to reopen or create another one. 

Cheers.
